export const ON_TASK_CREATE = 'ON_TASK_CREATE'
export const CREATE_TASK = 'CREATE_TASK'
export const ON_CREATE_TASK_ERROR = 'ON_CREATE_TASK_ERROR'

export const ON_FETCH_TASKS = 'ON_FETCH_TASKS'
export const FETCH_TASKS = 'FETCH_TASKS'
export const ON_FETCH_TASKS_ERROR = 'ON_FETCH_TASKS_ERROR'

export const ON_FETCH_SUBTASKS = 'ON_FETCH_SUBTASKS'
export const FETCH_SUBTASKS = 'FETCH_SUBTASKS'
export const ON_FETCH_SUBTASKS_ERROR = 'ON_FETCH_SUBTASKS_ERROR'

export const ON_DELETE_SUBTASK = 'ON_DELETE_SUBTASK'
export const DELETE_SUBTASK = 'DELETE_SUBTASK'
export const ON_DELETE_SUBTASK_ERROR = 'ON_DELETE_SUBTASK_ERROR'

export const ON_DELETE_TASK = 'ON_DELETE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const ON_DELETE_TASK_ERROR = 'ON_DELETE_SUBTASK_ERROR'

export const ON_SORT_TASKS = 'ON_SORT_TASKS'
